# This is a basic workflow to help you get started with Actions

name: Repo Star Notify


on:
  push:

    tags:
      - 'v*'


    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Star Count
        id: repo-stars
        uses: alanhg/repo-star-count-action@master
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ARPT-Bot 更新了！！！ 
            更新内容:
            `${{ github.event.head_commit.message }}`
          format: markdown
            
            
          

  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"


